<h2>Lakeland Care and Support Services
<span>helping you to live <strong>your</strong> life <strong>your</strong> way!</span></h2>
<p>Lakeland Care is an established local company  committed to delivering excellent standards of care in the community. We  provide services to people of all ages and levels of disability. Lakeland  Care can help you with as little or as much support as you need to remain  independent in your own home.</p>

<table id="services-table">
	<tr>
		<td>
			<table>
				<tr>
					<td><img src="<?php echo $this->baseUrl('images/cta1.jpg'); ?>" alt="click here for more information" /></td>
				</tr>
				<tr>
					<td><span class="heading">Home Care</span></td>
				</tr>
				<tr>
					<td><a href="<?php echo $this->url(array('module' => 'default','controller'=>'services','action'=>'homecare'), null, FALSE); ?>"><p class="link">More information &gt;&gt;</p></a></td>
				</tr>
			</table>
		</td>
		<td>
			<table>
				<tr>
					<td><img src="<?php echo $this->baseUrl('images/cta2.jpg'); ?>" alt="click here for more information" /></td>
				</tr>
				<tr>
					<td><span class="heading">Physical Disabilities</span></td>
				</tr>
				<tr>
					<td><a href="<?php echo $this->url(array('module' => 'default','controller'=>'services','action'=>'physicaldisabilities'), null, FALSE); ?>"><p class="link">More information &gt;&gt;</p></a></td>
				</tr>
			</table>
		</td>
		<td>
			<table>
				<tr>
					<td><img src="<?php echo $this->baseUrl('images/liveincare.jpg'); ?>" alt="click here for more information" /></td>
				</tr>
				<tr>
					<td><span class="heading">Live In Care</span></td>
				</tr>
				<tr>
					<td><a href="<?php echo $this->url(array('module' => 'default','controller'=>'services','action'=>'liveincare'), null, FALSE); ?>"><p class="link">More information &gt;&gt;</p></a></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr><td>&nbsp;</td></tr>
	<tr>
		<td>
			<table>
				<tr>
					<td><img src="<?php echo $this->baseUrl('images/cta4.jpg'); ?>" alt="click here for more information" /></td>
				</tr>
				<tr>
					<td><span class="heading">Dementia Care</span></td>
				</tr>
				<tr>
					<td><a href="<?php echo $this->url(array('module' => 'default','controller'=>'services','action'=>'dementiacare'), null, FALSE); ?>"><p class="link">More information &gt;&gt;</p></a></td>
				</tr>
			</table>
		</td>
		<td>
			<table>
				<tr>
					<td><img src="<?php echo $this->baseUrl('images/snowdrops.jpg'); ?>" alt="click here for more information" /></td>
				</tr>
				<tr>
					<td><span class="heading">End of Life Care</span></td>
				</tr>
				<tr>
					<td><a href="<?php echo $this->url(array('module' => 'default','controller'=>'services','action'=>'endoflife'), null, FALSE); ?>"><p class="link">More information &gt;&gt;</p></a></td>
				</tr>
			</table>
		</td>
		<td>
			<table>
				<tr>
					<td><img src="<?php echo $this->baseUrl('images/learning_diff.jpg'); ?>" alt="click here for more information" width="138"/></td>
				</tr>
				<tr>
					<td><span class="heading">Learning Disabilities</span></td>
				</tr>
				<tr>
					<td><a href="<?php echo $this->url(array('module' => 'default','controller'=>'services','action'=>'learningdifficulties'), null, FALSE); ?>"><p class="link">More information &gt;&gt;</p></a></td>
				</tr>
			</table>
		</td>
	</tr>
</table>



<p>We&nbsp;have a&nbsp;strongly&nbsp;established  local reputation&nbsp;as a quality care provider, being the first choice for  many&nbsp;requiring care&nbsp;for themselves or&nbsp;a loved one. When you choose Lakeland Care you can be certain that you will receive&nbsp;the  very highest standards of service along with unrivalled customer care.</p>
<p><strong>Here at Lakeland Care:</strong></p>
<ul>
	<li>Your       needs come first and foremost in everything we do. </li>
	<li>We       recognise that you deserve a friendly, professional and reliable service       to help you&nbsp;live a fulfilled and happy life.</li>
	<li>Our       highly- trained, compassionate staff team will go the extra mile to meet       and exceed your expectations.</li>
	<li>We&nbsp;genuinely&nbsp;care       about you and your loved ones and will &nbsp;provide you with individual and       personalised &nbsp;support that is second to none. </li>
</ul>

<h4>Quality Assurance and Compliance</h4>
<p>Lakeland Care &amp; Support Services Limited is  registered with, and therefore licensed to provide services, by the <a href="http://www.cqc.org.uk/" target="_blank">Care Quality Commission</a>.  To view our latest inspection report, please <a href="assets/CQC%20Report_Lakeland%20Care.pdf" target="_blank">click here</a>.</p> 


<?php echo $this->content; ?>