<h2>Meet the team</h2>
<h5>Expert Health & Social Care Professionals, dedicated to making a difference to your life</h5>

<?php echo $this->content; ?>

<div class="team">
	<div class="team-data">
		<img width="194" height="175" alt="Tina" src="<?php echo $this->baseUrl('images/team_marge.jpg'); ?>">
		<h4>Marge Smyth</h4>
		<p>Managing Director</p>
	</div>
</div>

<div class="team">
	<div class="team-data">
		<img width="194" height="175" alt="Tina" src="<?php echo $this->baseUrl('images/team_jo.jpg'); ?>">
		<h4>Jo Ward</h4>
		<p>Operational Manager</p>
	</div>
</div>

<div class="team">
	<div class="team-data">
		<img width="194" height="175" alt="Tina" src="<?php echo $this->baseUrl('images/team_tina.jpg'); ?>">
		<h4>Tina Gilmour</h4>
		<p>Care Services Manager</p>
	</div>
</div>

<div class="team">
	<div class="team-data">
		<img width="194" height="175" alt="Tina" src="<?php echo $this->baseUrl('images/team_ange.jpg'); ?>">
		<h4>Angela Lewns</h4>
		<p>Care Services Manager</p>
	</div>
</div>

<center>
	<img width="400" alt="Staff Members" src="<?php echo $this->baseUrl('images/staff.jpg'); ?>">
	<p>A few of our wonderful staff</p>
</center>