<?php ?>
<h2>Testimonials</h2>

<p class="breadcrumb">
	You are here: Testimonials
</p>

<table id="display-table" class="display" cellpadding="0" cellspacing="0" border="0">
	<thead>
		<tr>
			<th>From Person</th>
			<th>Date Added</th>
			<th>Last Updated</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach($this->testimonials as $testimonial) {?>
		<tr>
			<td><?php echo $testimonial['testimonial_author']; ?></td>
			<td><?php echo date('d-M-Y', strtotime($testimonial['date_added'])); ?></td>
			<td>
				<?php 
					$days = round((time() - strtotime($testimonial['last_update']))/86400);
					echo ($days > 1) ? $days." days ago" : "Today";
				?>
			</td>
			<td>
				<a href="<?php echo $this->url(array('module'=>'admin', 'controller'=>'testimonials', 'action'=>'update', 'testimonial'=>$testimonial['id'])); ?>">Edit</a> | 
				<a class="delete-confirm" href="<?php echo $this->url(array('module'=>'admin', 'controller'=>'testimonials', 'action'=>'delete', 'testimonial'=>$testimonial['id'])); ?>">Delete</a>
			</td>
		</tr>
			
	<?php } ?>
	</tbody>
</table>

<div id="confirm_delete">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>This testimonial will be permanently deleted and cannot be recovered. Are you sure?</p>
</div>