<h2>Contact details</h2>
<p>
	Lakeland Care &amp; Support Services Limited<br>
	Marl Business Park<br>
	Morecambe Road<br>
	Ulverston<br>
	Cumbria<br>
	LA12 9BN<br>
</p>
<p>
	Telephone: 01229 585693<br>
	Fax: 01229 480050
</p>
<p>Email: <a href="mailto:admin@lakelandcarers.co.uk">admin@lakelandcarers.co.uk</a></p>

<iframe width="642" height="450" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.co.uk/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=lakeland+care+support&amp;aq=&amp;sll=53.800651,-4.064941&amp;sspn=23.121255,39.770508&amp;vpsrc=6&amp;ie=UTF8&amp;hq=lakeland+care+support&amp;hnear=&amp;t=m&amp;cid=15326086781443670351&amp;ll=54.199755,-3.08218&amp;spn=0.022593,0.055103&amp;z=14&amp;iwloc=A&amp;output=embed"></iframe>
