<p>Whatever your requirements, our quality service will meet your individual needs.</p>
<table id="services-table">
	<tr>
		<td>
			<table>
				<tr>
					<td><img src="<?php echo $this->baseUrl('images/cta1.jpg'); ?>" alt="click here for more information" /></td>
				</tr>
				<tr>
					<td><span class="heading">Home Care</span></td>
				</tr>
				<tr>
					<td><a href="<?php echo $this->url(array('module' => 'default','controller'=>'services','action'=>'homecare'), null, FALSE); ?>"><p class="link">More information &gt;&gt;</p></a></td>
				</tr>
			</table>
		</td>
		<td>
			<table>
				<tr>
					<td><img src="<?php echo $this->baseUrl('images/cta2.jpg'); ?>" alt="click here for more information" /></td>
				</tr>
				<tr>
					<td><span class="heading">Physical Disabilities</span></td>
				</tr>
				<tr>
					<td><a href="<?php echo $this->url(array('module' => 'default','controller'=>'services','action'=>'physicaldisabilities'), null, FALSE); ?>"><p class="link">More information &gt;&gt;</p></a></td>
				</tr>
			</table>
		</td>
		<td>
			<table>
				<tr>
					<td><img src="<?php echo $this->baseUrl('images/cta3.jpg'); ?>" alt="click here for more information" /></td>
				</tr>
				<tr>
					<td><span class="heading">Live In Care</span></td>
				</tr>
				<tr>
					<td><a href="<?php echo $this->url(array('module' => 'default','controller'=>'services','action'=>'liveincare'), null, FALSE); ?>"><p class="link">More information &gt;&gt;</p></a></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr><td>&nbsp;</td></tr>
		<tr>
		<td>
			<table>
				<tr>
					<td><img src="<?php echo $this->baseUrl('images/cta4.jpg'); ?>" alt="click here for more information" /></td>
				</tr>
				<tr>
					<td><span class="heading">Dementia Care</span></td>
				</tr>
				<tr>
					<td><a href="<?php echo $this->url(array('module' => 'default','controller'=>'services','action'=>'dementiacare'), null, FALSE); ?>"><p class="link">More information &gt;&gt;</p></a></td>
				</tr>
			</table>
		</td>
		<td>
			<table>
				<tr>
					<td><img src="<?php echo $this->baseUrl('images/snowdrops.jpg'); ?>" alt="click here for more information" /></td>
				</tr>
				<tr>
					<td><span class="heading">End of Life Care</span></td>
				</tr>
				<tr>
					<td><a href="<?php echo $this->url(array('module' => 'default','controller'=>'services','action'=>'endoflife'), null, FALSE); ?>"><p class="link">More information &gt;&gt;</p></a></td>
				</tr>
			</table>
		</td>
		<td>
			<table>
				<tr>
					<td><img src="<?php echo $this->baseUrl('images/learning_diff.jpg'); ?>" alt="click here for more information" width="138"/></td>
				</tr>
				<tr>
					<td><span class="heading">Learning Disabilities</span></td>
				</tr>
				<tr>
					<td><a href="<?php echo $this->url(array('module' => 'default','controller'=>'services','action'=>'learningdifficulties'), null, FALSE); ?>"><p class="link">More information &gt;&gt;</p></a></td>
				</tr>
			</table>
		</td>
	</tr>
</table>